# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmonitor.proto"\x1e\n\x0eMonitorRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t"\x1f\n\x0cMonitorReply\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x07Monitor\x12,\n\x08SendData\x12\x0f.MonitorRequest\x1a\r.MonitorReply"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "monitor_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _MONITORREQUEST._serialized_start = 17
    _MONITORREQUEST._serialized_end = 47
    _MONITORREPLY._serialized_start = 49
    _MONITORREPLY._serialized_end = 80
    _MONITOR._serialized_start = 82
    _MONITOR._serialized_end = 137
# @@protoc_insertion_point(module_scope)
